### ISSUE TITLE
Problems with running Bartacus

### ISSUE THREAD

**Issue by robert197** [Bartacus/BartacusBundle#1]
We just wanted to try out Bartacus once with the method which is described in your documentation and than also with the command  `create-project --dev bartacus/bartacus-standard myproject`. Both methods showed us the same error... 

`Fatal error: Class 'Doctrine\Common\Annotations\AnnotationRegistry' not found in /home/dev/git/comsolit/test-bartacus/typo3conf/AdditionalConfiguration.php on line 8`

we noticed, that in the mehtod `initializeComposerClassLoader()` the variable 
TYPO3_COMPOSER_AUTOLOAD isn't set. 

autoload.php from Packeges/Libaries/ and from contrib/vendor/ exsits.

**Comment by patkar** [comment]
Does you webserver config supports `SetEnv` in the [`.htaccess`](https://github.com/Bartacus/Bartacus-Standard/blob/master/.htaccess#L9)? Otherwise you must the the `TYPO3_COMPOSER_AUTOLOAD` environment variable in you webserver config directly.

Sadly this is the only way in TYPO3 6.2 to support your own `composer.json` and vendors.

**Comment by robert197** [comment]
nope its still not working. TYPO3_COMPOSER_AUTOLOAD env is now true but i still get this error

**Comment by patkar** [comment]
Can you show me the output of `composer show -i`?

**Comment by robert197** [comment]
shows nothing. there is nothing installed

**Comment by patkar** [comment]
Ok, a `composer install` is mandatory :grinning: 

Altough a `composer create-project` should issue one.. Strange

**Comment by robert197** [comment]
oh, it does :dancer: 
it was my first time using composer. Maybe you should expand your readme/documentation :D

**Comment by patkar** [comment]
yaayy :sweat_smile:

Doc improvements are on the way, but my spare time is rare atm.

**Comment by robert197** [comment]
one more short question. Have you maybe an example for a ForntendHelper class? which i have to include into config.yml.... 
thank you very much for your support!!

**Comment by patkar** [comment]
You mean like in http://bartacus.readthedocs.org/en/latest/services_typoscript.html ?

It's only a example. This class can be anything with methods doing anything ;)

**Comment by robert197** [comment]
Understood :+1: thank you for this feature
