### ISSUE TITLE
Patching fails for typo3/cms-cli

### ISSUE THREAD

**Issue by mmunz** [Bartacus/BartacusBundle#111]
It seems the branch name on TYPO3/cms-cli was renamed to main, therefore the patch for "Patch entry point for proper Symfony :kernel bootstrap" fails:

```
- Applying patches for typo3/cms-cli
    https://github.com/TYPO3/cms-cli/compare/master...Bartacus:patch/2.0.0/bartacus-entry-script.patch (Patch entry point for proper Symfony kernel bootstrap)
   Could not apply patch! Skipping. The error was: The "https://github.com/TYPO3/cms-cli/compare/master...Bartacus:patch/2.0.0/bartacus-entry-script.patch" file could not be downloaded (HTTP/1.1 404 Not Found)

In Patches.php line 331:
                                                                                                                                                                                  
  Cannot apply patch Patch entry point for proper Symfony kernel bootstrap (https://github.com/TYPO3/cms-cli/compare/master...Bartacus:patch/2.0.0/bartacus-entry-script.patch)!  
                                                                                                                                                                                  
```

Changing the branch to main in composer.json fixes the problem, i.e. use:

```
"typo3/cms-cli": {
                "Patch entry point for proper Symfony kernel bootstrap": "https://github.com/TYPO3/cms-cli/compare/main...Bartacus:patch/2.0.0/bartacus-entry-script.patch"
            },
```

**Comment by mmunz** [comment]
Found another problem: With typo3/cms-cli v3.1.1 the file to patch (typo3 cli) has been changed and the patch does not apply anymore, see https://github.com/TYPO3/cms-cli/commit/2fb4106dcc14163feebf0829ca2d8021c346db32

**Comment by Aricura** [comment]
The problem has been solved in multiple Bartacus versions to ensure compatiblity with older TYPO3 projects. Please use one of the following version depending on your TYPO3 installation:
- TYPO3 v10.4.* = BartacusBundle version 3.1.6 or higher (TYPO3 cms-cli needs to be at least 2.0.0)
- TYPO3 v11.5.* = BartacusBundle version 3.3.1 or higher (TYPO3 cms-cli needs to be at least 3.1.1)
- TYPO3 v12.4.* = BartacusBundle version 4.0.1 or higher (TYPO3 cms-cli needs to be at least 3.1.1)
