### ISSUE TITLE
Handle 404 responses within frontend-plugins

### ISSUE THREAD

**Issue by thasmo** [Bartacus/BartacusBundle#2]
It would be nice if Bartacus could intercept 404 responses within frontend controller actions and optionally call `pageNotFoundAndExit` to render the global 404 error page of TYPO3.

#### Actual Behavior
Bartacus handles the 404 response as emptry string and TYPO3 renders the normal frontend.

#### Expected Behavior
Bartacus intercepts/detects the 404 response and calls `pageNotFoundAndExit` so TYPO3 will use it's `PageNotFoundHandler` to render the actual 404 page.

**Comment by patkar** [comment]
Will be done in new 1.0.0 release for TYPO3 8.x, but maybe not as expected :grin:
