### ISSUE TITLE
app/ext_localconf.php is not executed

### ISSUE THREAD

**Issue by jdkpix** [Bartacus/BartacusBundle#55]
directions in app/ext_localconf.php are not applied upon cache refresh

**Comment by patkar** [comment]
Since update to TYPO3 8.6 with #65 the `app/ext_localconf.php` is not executed anymore in general :sob:

**Comment by patkar** [comment]
Ok, me is wrong :face_with_head_bandage: `app/ext_localconf.php` was never executed :(

**Comment by patkar** [comment]
This shouldn't be closed, even if there is a workaround :smirk:

**Comment by patkar** [comment]
Not worth fixing, as the workaround is good enough. It may be ugly, but it works. Fixing that would require either patching the Bootstrap of TYPO3 or using AOP on vendor files. That's more ugly..
