### ISSUE TITLE
Handle 404 content element responses

### ISSUE THREAD

**Issue by patkar** [Bartacus/BartacusBundle#6]
as in #2

**Comment by patkar** [comment]
Using `pageNotFoundAndExit` to use TYPO3 configured `PageNotFoundHandler`?
Or using symfony standard exception handling? -> which implies TYPO3 must be changed to use Symfony 404/exception handling.

**Comment by thasmo** [comment]
Definition of the 404 page would be nice via
- a route (i.e. controller action), as a powerful/flexible solution
- a pre-configured template, as an out-of-the-box solution.

**Comment by patkar** [comment]
@thasmo: That would be the standard symfony way. Which implies as said above, the `PageNotFoundHandler` must be piped into symfony.

See http://symfony.com/doc/current/controller/error_pages.html how to override only the exception template and how to define your own exception controller action.
